### ISSUE TITLE
racing.py solve failed

### ISSUE THREAD

**Issue by maozaizhou** [HybridRobotics/car-racing#5]
**System information**
OS Platform and Distribution (e.g., Linux Ubuntu 18.04): Linux Ubuntu 18.04
Branch: master
Steps to reproduce the issue:
python examples/racing.py --simulation --plotting --animation

**Error detail:**
Car-Racing/src/policy.py", line 224, in calc_input
    sol = opti.solve()

RuntimeError: Error in Opti::solve [OptiNode] at .../casadi/core/optistack.cpp:159:
.../casadi/core/optistack_internal.cpp:999: Assertion "return_success(accept_limit)" failed:
Solver failed. You may use opti.debug.value to investigate the latest values of variables. return_status is 'Infeasible_Problem_Detected'

Dear Jun Zeng, there some error when running racing.py example, I'm wondering if it's a bug or just some error cause by casadi.

**Comment by junzengx14** [comment]
Thank you for your issue, actually the error could occur randomly due to some infeasibility issue of our proposed approach described in our ACC paper [link](https://arxiv.org/abs/2007.11718), this issue is addressed in our later theoretical work which will appear in CDC [link](https://arxiv.org/abs/2105.10596) this year.

We will update the code pretty soon together with new submitted paper, where problem will be resolved and much better racing behavior will be carried out. I will ping again this thread once we upload things.

**Comment by maozaizhou** [comment]
cool,I'm new to CBF algorithm,but I use casadi a lot, maybe I can do some contribution to this repo in the future when getting more deep into CBF.

**Comment by junzengx14** [comment]
> cool,I'm new to CBF algorithm,but I use casadi a lot, maybe I can do some contribution to this repo in the future when getting more deep into CBF.

Thank for your interests! That's awesome, we will have a big new release before Christmas (expected) together with our ICRA paper. I will let you know in this issue.

**Comment by junzengx14** [comment]
The paper is released in https://arxiv.org/abs/2112.06435, code will be released very soon.

**Comment by maozaizhou** [comment]
@junzengx14 Nice work, happy holidays by the way.

**Comment by junzengx14** [comment]
The latest version is released.
